blueprint:
  name: Sensor Activated Output
  description: >
    Turn on output when sensor is detected.

    Four different scenes can be defined depending on time of day.

    Features:
     - Trigger on sense (anything that switches between “on” and off")
     - Wait time for turning off
     - Only run if entity is in desired state (optional)
     - Sun elevation check (optional)
     - 4 Scenes for different times of day (optional)
     - Ambient support with time frame (optional)
     - Default scene when sense stops (optional)
     - “no sense blocker” with user choosable state (optional)
  domain: automation
  source_url: https://github.com/ptdomotics/home-assistant.git/blueprints/sensor-activated-output.yaml
  author: PTDomotics
  input:
    sense_entity:
      name: Trigger Sensor
      description: Trigger Sensor (anything switching between "on" and "off")
      selector:
        entity:
    output_target:
      name: Output
      selector:
        target:
          entity:
            domain:
              - light
              - switch
    no_sense_wait:
      name: Wait time
      description: Time to leave the output "on" after last sense is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    automation_blocker:
      name: Automation Blocker (Optional)
      description: Only run if this boolean is in desired state (see next input)
      default:
      selector:
        entity:
    automation_blocker_boolean:
      name: Automation Blocker Chooser (Optional)
      description: Desired state of automation blocker, choose on for on and off for off
      default: false
      selector:
        boolean:
    no_sense_blocker:
      name: No Sense Blocker (Optional)
      description: No sense sequence is not run if this boolean is in desired state (see next input)
      default:
      selector:
        entity:
    no_sense_blocker_boolean:
      name: No Sense Chooser (Optional)
      description: Desired state of no sense blocker, choose on for on and off for off
      default: false
      selector:
        boolean:
    elevation_check:
      name: Sun elevation check (Optional)
      description: This is the angle between the sun and the horizon. Negative values mean the sun is BELOW the horizon.
      default: none
      selector:
        number:
          min: -90
          max: 90
          unit_of_measurement: degrees
    scene_ambient:
      name: Ambient Scene (Optional)
      description: Scene for ambient state. Will be activated when no sense is detected.
      default: scene.none
      selector:
        entity:
          domain: scene
    time_scene_ambient_start:
      name: Ambient time frame start (Optional)
      description: Time from which on ambient scene will be activated
      default: "00:00:00"
      selector:
        time:
    time_scene_ambient_end:
      name: Ambient time frame end (Optional)
      description: Time from which on ambient scene will be not activated
      default: "00:00:00"
      selector:
        time:
    scene_morning:
      name: Scene for the morning (Optional)
      default: scene.none
      selector:
        entity:
          domain: scene
    time_scene_morning:
      name: Time for the morning scene (Optional)
      description: A time input which defines the time from which on the scene will be activated if sense is detected.
      default: "00:00:00"
      selector:
        time:
    scene_day:
      name: Scene for the bright day (Optional)
      default: scene.none
      selector:
        entity:
          domain: scene
    time_scene_day:
      name: Time for the day scene (Optional)
      description: A time input which defines the time from which on the scene will be activated if sense is detected.
      default: "00:00:00"
      selector:
        time:
    scene_evening:
      name: Scene for the evening (Optional)
      default: scene.none
      selector:
        entity:
          domain: scene
    time_scene_evening:
      name: Time for the evening scene (Optional)
      description: A time input which defines the time from which on the scene will be activated if sense is detected.
      default: "00:00:00"
      selector:
        time:
    scene_night:
      name: Scene for the dark night (Optional)
      default: scene.none
      selector:
        entity:
          domain: scene
    time_scene_night:
      name: Time for the night scene (Optional)
      description: A time input which defines the time from which on the scene will be activated if sense is detectedd.
      default: "00:00:00"
      selector:
        time:
    scene_no_sense:
      name: Default scene for no sense (Optional)
      description: Set this Scene if you want to activate a scene if sense stops
      default: scene.none
      selector:
        entity:
          domain: scene
mode: restart
max_exceeded: silent

variables:
  scene_ambient: !input scene_ambient
  scene_morning: !input scene_morning
  scene_day: !input scene_day
  scene_evening: !input scene_evening
  scene_night: !input scene_night
  automation_blocker: !input automation_blocker
  automation_blocker_boolean: !input automation_blocker_boolean
  no_sense_blocker: !input no_sense_blocker
  no_sense_blocker_boolean: !input no_sense_blocker_boolean
  elevation_check: !input elevation_check
  scene_no_sense: !input scene_no_sense
  sense_entity: !input sense_entity

trigger:
  - platform: state
    entity_id: !input sense_entity
    from: "off"
    to: "on"
  - platform: state
    entity_id: !input sense_entity
    from: "on"
    to: "off"
    for: !input no_sense_wait

condition:
  - condition: or
    conditions:
      - "{{ automation_blocker == none }}"
      - "{{ automation_blocker_boolean and states[automation_blocker].state == 'on' }}"
      - "{{ not automation_blocker_boolean and states[automation_blocker].state == 'off' }}"
  - condition: template
    value_template: "{{ (elevation_check == none) or (state_attr('sun.sun','elevation') <= elevation_check | float(90)) }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ scene_morning != 'scene.none'}}"
                  - condition: time
                    after: !input time_scene_morning
                    before: !input time_scene_day
                sequence:
                  - scene: !input scene_morning
              - conditions:
                  - "{{ scene_day != 'scene.none'}}"
                  - condition: time
                    after: !input time_scene_day
                    before: !input time_scene_evening
                sequence:
                  - scene: !input scene_day
              - conditions:
                  - "{{ scene_evening != 'scene.none'}}"
                  - condition: time
                    after: !input time_scene_evening
                    before: !input time_scene_night
                sequence:
                  - scene: !input scene_evening
              - conditions:
                  - "{{ scene_night != 'scene.none'}}"
                  - condition: time
                    after: !input time_scene_night
                    before: !input time_scene_morning
                sequence:
                  - scene: !input scene_night
            default:
              - service: homeassistant.turn_on
                target: !input output_target
      - conditions:
          - condition: template
            value_template: "{{ trigger.to_state.state == 'off' }}"
          - condition: or
            conditions:
              - "{{ no_sense_blocker == none }}"
              - "{{ no_sense_blocker_boolean and states[no_sense_blocker].state == 'on' }}"
              - "{{ not no_sense_blocker_boolean and states[no_sense_blocker].state == 'off' }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ scene_ambient != 'scene.none' }}"
                  - condition: time
                    after: !input time_scene_ambient_start
                    before: !input time_scene_ambient_end
                sequence:
                  - scene: !input scene_ambient
              - conditions:
                  - "{{ scene_no_sense != 'scene.none' }}"
                sequence:
                  - scene: !input scene_no_sense
            default:
              - service: homeassistant.turn_off
                target: !input output_target
